### ISSUE TITLE
gcal plugin fails to start without siteurl but still appears enabled

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/mattermost-plugin-google-calendar#72]
With the siteURL blank in Mattermost the gcal plugin appears to start, but in fact it crashes. 

```json
{"timestamp":"2024-05-01 19:36:14.820 Z","level":"info","msg":"[ERROR] call to OnConfigurationChange failed, error: plugin requires Mattermost Site URL to be set","caller":"io/io.go:429","plugin_id":"com.mattermost.gcal","source":"plugin_stderr"}
{"timestamp":"2024-05-01 19:36:14.820 Z","level":"info","msg":"[ERROR] call to OnConfigurationChange failed, error: plugin requires Mattermost Site URL to be set","plugin_id":"com.mattermost.gcal","source":"plugin_stderr"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"panic: runtime error: invalid memory address or nil pointer dereference","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.gcal"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x107af61]","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.gcal"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.gcal"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"goroutine 42 [running]:","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.gcal"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.mattermost.gcal"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x107af61]","plugin_id":"com.mattermost.gcal"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"","plugin_id":"com.mattermost.gcal"}
{"timestamp":"2024-05-01 19:36:14.825 Z","level":"debug","msg":"goroutine 42 [running]:","plugin_id":"com.mattermost.gcal"}

{"timestamp":"2024-05-01 19:36:44.413 Z","level":"debug","msg":"Deactivating plugin due to multiple crashes","id":"com.mattermost.gcal"}

```

Ideally, you can't even enable to gcal plugin without setting the siteurl

**Comment by darias416** [comment]
Confirmed this is an issue being experienced by another Enterprise customer.
